#### scan
POST http://192.168.14.202:10067/ HTTP/1.1
content-type: application/json

[
    "--scan"
]

#### buh url test
POST http://192.168.14.202:10067/ HTTP/1.1
content-type: application/json

[
    "--address",
    "FB:8C:90:54:54:45",
    "--set-gif",
    "https://cdn.7tv.app/emote/01GQFT1WF80002Q9KS8SKQMHHY/1x.gif",
    "--process-gif",
    "64"
]

#### local gif test
POST http://192.168.14.202:10067/ HTTP/1.1
content-type: application/json

[
    "--address",
    "FB:8C:90:54:54:45",
    "--set-gif",
    "images/demo.gif",
    "--process-gif",
    "64"
]

##